src/Entity/Actualite.php
<?php

namespace App\Entity;

use DateTime;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ActualiteRepository")
 */
class Actualite
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="actualites")
     */
    private $id_user;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Commentaire", mappedBy="id_actualite", orphanRemoval=true)
     */
    private $commentaires;


    public function __construct()
    {
        $this->date= new DateTime();
        $this->commentaires = new ArrayCollection();
    }

    public function getId(): int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(?string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getIdUser(): ?User
    {
        return $this->id_user;
    }

    public function setIdUser(?User $id_user): self
    {
        $this->id_user = $id_user;

        return $this;
    }

    public function getDate($format = 'd-m-y à H:i:s')
    {
        return $this->date->format($format);
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }


    /**
     * @return Collection|null
     */
    public function getCommentaires(): ?Collection
    {
        return $this->commentaires;
    }

    /**
     * @param Commentaire $commentaire
     * @return Actualite
     */
    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaires->contains($commentaire)) {
            $this->commentaires[] = $commentaire;
            $commentaire->setIdActualite($this);

        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaires->contains($commentaire)) {
            $this->commentaires->removeElement($commentaire);
            // set the owning side to null (unless already changed)
            if ($commentaire->getIdActualite() === $this) {
                $commentaire->setIdActualite(null);
            }
        }

        return $this;
    }


    /**
     * @return mixed
     */
    public function __toString():string
    {
        return $this->titre;
    }

}

src/Form/ActualiteType.php
<?php

namespace App\Form;

use App\Entity\Actualite;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ActualiteType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre',TextType::class,[
                'label'=>'Titre: '
            ])
            ->add('image', FileType::class,array(
                'data_class' => null,
                'label'=>'Photo:',
                'required'   => false,))
            ->add('description',TextType::class,array(
                'required'=>false,
                'label'=>'Dire plus:',
                ))

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Actualite::class,
        ]);
    }
}

src/Controller/ActualiteController.php
<?php

namespace App\Controller;

use App\Entity\Actualite;
use App\Entity\Commentaire;
use App\Entity\User;
use App\Form\ActualiteType;
use App\Form\CommentaireType;
use App\Repository\ActualiteRepository;
use App\Repository\CommentaireRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/actualite")
 */
class ActualiteController extends AbstractController
{

    /**
     * @Route("/", name="actualite_index", methods={"GET","POST"})
     * @param Request $request
     * @param ActualiteRepository $actualiteRepository
     * @param $titre
     * @return Response
     */
    public function index(Request $request,ActualiteRepository $actualiteRepository): Response
    {
        $user= $this->getUser();
        $actualite = new Actualite();
        $commentaire= new Commentaire();
        //Formulaires des actualites
        $formActualite = $this->createForm(ActualiteType::class, $actualite);
        $formActualite->handleRequest($request);
        //Formulaire commentaire
        $formCommentaire = $this->createForm(CommentaireType::class, $commentaire);
        $formCommentaire->handleRequest($request);
        //On vérifie le formulaire d'actualité
        if ($formActualite->isSubmitted() && $formActualite->isValid())
        {
            /** @var UploadedFile $photo */
            $photo = $formActualite['image']->getData();

            if ($photo)
            {
                $originalFilename = pathinfo($photo->getClientOriginalName(), PATHINFO_FILENAME);

                //$safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $originalFilename . '-' . uniqid() . '.' . $photo->guessExtension();

                try
                {
                    $photo->move($this->getParameter('image_directory'), $newFilename);
                }

                catch (FileException $e)
                {

                }
                $actualite->setImage($newFilename);

            }
            $actualite->setIdUser($user);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($actualite);
            $entityManager->flush();
        }
        //vérifie formulaire des commentaires
        if ($formCommentaire->isSubmitted() && $formCommentaire->isValid()) {

            $commentaire->setIdUser($user);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($commentaire);
            $entityManager->flush();

        }

             return $this->render('actualite/index.html.twig', [
            'actualites' => $actualiteRepository->getCustomActualite(),
            'formActualite' => $formActualite->createView(),
            'formCommentaire' => $formCommentaire->createView(),

        ]);
    }

    /**
     * @Route("/new", name="actualite_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $actualite = new Actualite();
        $user= $this->getUser();
        $form = $this->createForm(ActualiteType::class, $actualite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $photo */
            $photo = $form['image']->getData();

            if ($photo)
            {
                $originalFilename = pathinfo($photo->getClientOriginalName(), PATHINFO_FILENAME);

                //$safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $originalFilename . '-' . uniqid() . '.' . $photo->guessExtension();

                try
                {
                    $photo->move($this->getParameter('image_directory'), $newFilename);
                }

                catch (FileException $e)
                {

                }
                $actualite->setImage($newFilename);

            }

            $actualite->setIdUser($user);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($actualite);
            $entityManager->flush();
            return $this->redirectToRoute('actualite_index');
        }

        return $this->render('actualite/new.html.twig', [
            'actualite' => $actualite,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="actualite_show", methods={"GET","POST"})
     * @param Actualite $actualite
     * @param Request $request
     * @param ActualiteRepository $actualiteRepository
     * @return Response
     */
        public function show(Actualite $actualite,Request $request,ActualiteRepository $actualiteRepository): Response
        {
            if (!$actualite) {
                throw $this->createNotFoundException('Aucun article trouvé');

            }
            $user= $this->getUser();
            $newCommentaire = new Commentaire();
            $form = $this->createForm(CommentaireType::class, $newCommentaire);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
//                /** @var UploadedFile $photo */
//                $photo = $form['image']->getData();
//
//                if ($photo)
//                {
//                    $originalFilename = pathinfo($photo->getClientOriginalName(), PATHINFO_FILENAME);
//
//                    //$safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
//                    $newFilename = $originalFilename . '-' . uniqid() . '.' . $photo->guessExtension();
//
//                    try
//                    {
//                        $photo->move($this->getParameter('image_directory'), $newFilename);
//                    }
//
//                    catch (FileException $e)
//                    {
//
//                    }
//                    $newCommentaire->setImage($newFilename);
//
//                }
                $newCommentaire->setIdUser($user);
                $newCommentaire->setIdActualite($actualite);
                $entityManager = $this->getDoctrine()->getManager();
                $entityManager->persist($newCommentaire);
                $entityManager->flush();
                $this->get('session')->getFlashBag()->add('info', 'Commentaire bien ajouté');
            }

            return $this->render('actualite/show.html.twig', [
                'actualite' => $actualite,
                'form' => $form->createView(),

            ]);
        }

    /**
     * @Route("/{id}/edit", name="actualite_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Actualite $actualite): Response
    {
        $form = $this->createForm(ActualiteType::class, $actualite);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var UploadedFile $photo */
            $photo = $form['image']->getData();

            if ($photo)
            {
                $originalFilename = pathinfo($photo->getClientOriginalName(), PATHINFO_FILENAME);

                //$safeFilename = transliterator_transliterate('Any-Latin; Latin-ASCII; [^A-Za-z0-9_] remove; Lower()', $originalFilename);
                $newFilename = $originalFilename . '-' . uniqid() . '.' . $photo->guessExtension();

                try
                {
                    $photo->move($this->getParameter('image_directory'), $newFilename);
                }

                catch (FileException $e)
                {

                }
                $actualite->setImage($newFilename);

            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($actualite);
            $entityManager->flush();
            return $this->redirectToRoute('actualite_index');
        }

        return $this->render('actualite/edit.html.twig', [
            'actualite' => $actualite,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="actualite_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Actualite $actualite): Response
    {
        if ($this->isCsrfTokenValid('delete'.$actualite->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($actualite);
            $entityManager->flush();
        }

        return $this->redirectToRoute('actualite_index');
    }
}

templates/actualite/_delete_form.html.twig
<form method="post" action="{{ path('actualite_delete', {'id': actualite.id}) }}" onsubmit="return confirm('Voulez vous vraiment supprimer votre article?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ actualite.id) }}">
    <button class="btn"><i class="fa fa-trash-alt"></i> Delete</button>
</form>

templates/actualite/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Enregistrer') }}</button>
{{ form_end(form) }}

templates/actualite/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Actualite{% endblock %}

{% block body %}

<div class="row card-body" style="background-color: #222222">
    <div class="col-sm-5 col-lg-5" style="margin-left: auto;margin-right: auto;margin-bottom: 50px;width:500px;background-color: white">

        <div class="row">
            <div class="col-6">
                <h2>
                    <img src="{{asset('uploads/photo/'~actualite.iduser.photo )}}" width="auto" height="100px" style="border-radius: 100%">
                    {{ actualite.iduser }}
                </h2>
            </div>
            <div class="col-6" align="right">

            </div>
        </div>
        <br>
        <p class="card-text">{{ actualite.titre }}</p>
        <p class="card-text disabled">{{ actualite.date }} <i class="fas fa-globe-europe"></i> </p>
        <div class="card">
            {% if  actualite.image!= null%}
                <img class="card-img-center" alt="Card image" src="{{asset('uploads/images/'~actualite.image )}}" width="100%" >
                <br>
            {% endif %}
            {% if  actualite.description!= null%}
                <div class="card-body">
                    <p class="card-text">{{ actualite.description }}</p>
                </div>
            {% endif %}
        </div>
    </div>
    <div class="col-sm-5 col-lg-5" style="margin-left: auto;margin-right: auto;margin-bottom: 50px;width:500px;background-color: white">
            {{ form_start(form) }}
            <div class="form-group">
                {{ form_widget(form) }}
            </div>
            <div class="form-group" align="center">
                <button class="btn btn-success" align="center">{{ button_label|default('Modifier') }}</button>
            </div>
            {{ form_end(form) }}
    </div>


</div>


{% endblock %}

templates/actualite/index.html.twig
{% block body %}
    <br>
    <div class="container mt-3" align="center">
        <!-- Button to Open the Modal -->
        Ajouter un article

        <button type="button" class="btn btn-info" data-toggle="modal" data-target="#myModal">
            <i class="fas fa-plus-circle"></i>
        </button>

        <!-- The Modal -->
        <div class="modal fade" id="myModal">
            <div class="modal-dialog">
                <div class="modal-content">

                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">Partager nous une pensée ou idée!</h4>
                        <button type="button" class="close" data-dismiss="modal">×</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        {{ form_start(formActualite) }}
                        {{ form_widget(formActualite) }}
                        <button class="btn btn-success">{{ button_label|default('Enregister') }}</button>
                        {{ form_end(formActualite) }}
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <br><br><br>
    {% for actualite in actualites %}
        <div class="row card-body">
            <div class="col-xs-8 col-sm-8 col-lg-8" style="margin-left: auto;margin-right: auto">
                <div class="row">
                    <div class="col-6">
                        <h2>
                            <img src="{{asset('uploads/photo/'~actualite.iduser.photo )}}" width="auto" height="100px" style="border-radius: 100%">
                            {{ actualite.iduser }}
                        </h2>
                    </div>

                    <div class="col-6" align="right">
                        {% if app.user == actualite.iduser %}
                            <div class="dropdown dropdown-menu-left">
                                <button type="button" class="btn toggle" data-toggle="dropdown">
                                    <i class="fa fa-align-justify"></i>
                                </button>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="#"> {{ include('actualite/_delete_form.html.twig')}}</a>
                                    <a  class="dropdown-item info"  href="{{ path('actualite_edit', {'id': actualite.id}) }}" ><i class="fas fa-edit"></i>Modifier</a>
                                </div>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <br>
                <p class="card-text">{{ actualite.titre }}</p>
                <p class="card-text disabled">{{ actualite.date }} <i class="fas fa-globe-europe"></i> </p>
                <div class="card">
                    {% if  actualite.image!= null%}
                        <img class="card-img-center" alt="Card image" src="{{asset('uploads/images/'~actualite.image )}}" width="100%" >
                    {% endif %}
                    {% if  actualite.description!= null%}
                        <div class="card-body">
                            <p class="card-text">{{ actualite.description }}</p>
                        </div>
                    {% endif %}
                    <div class="card-body">
                        <button type="button" class="btn btn-outline-info"  data-toggle="collapse" data-target="#commentaires">
                            <i class="fa fa-comment-dots">
                                ({{ actualite.getCommentaires|length }})
                            </i>
                            voir les commenatires

                        </button>
                        <a href="{{ path('actualite_show', {'id': actualite.id}) }}">
                            <button type="button" class="btn btn-outline-info" >

                            <i class="fa fa-pen">

                            </i>

                            Laisser un commentaire

                            </button>
                        </a>
                        {#//Les commentaires#}
                        <div id="commentaires" class="collapse" style="height: 10px">
                            <br>
                            {% for commentaire in actualite.getCommentaires %}
                            <div class="media border" style="background-color:ghostwhite ">
                                <img src="{{asset('uploads/photo/'~commentaire.idUser.photo )}}" alt="John Doe" class="ml-4 mt-2 rounded-circle" style="width:60px;">
                                <div class="media-body ml-4">
                                    <p class="card-text"><strong>{{ commentaire.idUser }}</strong> <small><br><i>Publié le {{ commentaire.date }}</i></small></p>
                                    <p class="card-text">{{ commentaire.libelle }}.</p><br>
                                </div>
                            </div><br>

                                {% else %}
                                <p>Soyez le premier à laisser un commentaire</p>
                                   <br>

                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>

    {% else %}
                <p >Soyez le premier à éditer un article</p>
    </div>
        <br><br><br>
    {% endfor %}
    <br><br><br>
{% endblock %}

templates/actualite/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Actualite{% endblock %}

{% block body %}
    <h1>Create new Actualite</h1>

    {{ include('actualite/_form.html.twig') }}

    <a href="{{ path('actualite_index') }}">back to list</a>
{% endblock %}

templates/actualite/show.html.twig
{% extends 'base.html.twig' %}
{% block body %}
    <!-- single -->
    <div class="single-page-artical">
        <div class="artical-content">
            <h3>{{ actualite.titre }}</h3>
            {% if  actualite.image!= null%}
            <img class="img-responsive" src="{{asset('uploads/images/'~actualite.image )}}" alt=" " />
            {% endif %}
            {% if  actualite.description!= null%}
            <p>
                {{ actualite.description }}
            </p>
            {% endif %}
        </div>
        <div class="artical-links">
            <ul>
                <li><small> </small><span>{{ actualite.date }}</span></li>
                <li><a href="#"><small class="admin"> </small><span>{{ actualite.iduser }}</span></a></li>
                <li><a href="#"><small class="no"> </small><span>({{ actualite.commentaires|length }}) commentaires</span></a></li>
            </ul>
        </div>
        {#        Les commentaires#}
        <div class="comment-grid-top">
            <h3>Commentaires</h3>
            {% for commentaire in actualite.getCommentaires %}
            <div class="comments-top-top">
                <div class="top-comment-left">
                    <a href="#"><img class="img-responsive" src="{{asset('uploads/photo/'~commentaire.idUser.photo )}}" alt=""></a>
                </div>
                <div class="top-comment-right">
                    <ul>
                        <li><span class="left-at"><a href="#">{{ commentaire.idUser }}</a></span></li>
                        <li><span class="right-at">{{ commentaire.date }}</span></li>
                    </ul>
                    <p>
                        {{ commentaire.libelle }}
                    </p>
                </div>
                <div class="clearfix"> </div>
            </div>
            {% else %}
            <div class="comments-top-top top-grid-comment">
                <div class="top-comment-left">
                </div>
                <div class="top-comment-right">
                    <p>Soyez le premier à laisser un commentaire</p>
                </div>
                <div class="clearfix"> </div>
            </div>
            {% endfor %}
            <div class="comments-top-top">
                <div class="top-comment-left">
                    <a href="#"><img class="img-responsive" src="{{asset('uploads/photo/'~app.user.photo )}}" alt="{{ app.user }}"></a>
                </div>
                <div class="top-comment-right">
                    {{ form_start(form) }}
                    <p>
                        {{ form_row(form.libelle) }}<button class="btn btn-success">{{ button_label|default('Commenter') }}</button>
                    </p>
                    {{ form_end(form) }}
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>
    </div>
    <!-- single -->
{% endblock %}